package com.test.mybatis.mapper;

import com.test.mybatis.po.Ghistorymessage;
import com.test.mybatis.po.GhistorymessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GhistorymessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    long countByExample(GhistorymessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int deleteByExample(GhistorymessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int insert(Ghistorymessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int insertSelective(Ghistorymessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    List<Ghistorymessage> selectByExampleWithBLOBs(GhistorymessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    List<Ghistorymessage> selectByExample(GhistorymessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    Ghistorymessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") Ghistorymessage record, @Param("example") GhistorymessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Ghistorymessage record, @Param("example") GhistorymessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByExample(@Param("record") Ghistorymessage record, @Param("example") GhistorymessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByPrimaryKeySelective(Ghistorymessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Ghistorymessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ghistorymessage
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByPrimaryKey(Ghistorymessage record);
}