package com.test.mybatis.mapper;

import com.test.mybatis.po.Ptphismes;
import com.test.mybatis.po.PtphismesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtphismesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    long countByExample(PtphismesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int deleteByExample(PtphismesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int insert(Ptphismes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int insertSelective(Ptphismes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    List<Ptphismes> selectByExampleWithBLOBs(PtphismesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    List<Ptphismes> selectByExample(PtphismesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    Ptphismes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") Ptphismes record, @Param("example") PtphismesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Ptphismes record, @Param("example") PtphismesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByExample(@Param("record") Ptphismes record, @Param("example") PtphismesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByPrimaryKeySelective(Ptphismes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Ptphismes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptphismes
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    int updateByPrimaryKey(Ptphismes record);
}