package com.test.mybatis.mapper;

import com.test.mybatis.po.TUser;
import com.test.mybatis.po.TUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	long countByExample(TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int deleteByExample(TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int insert(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int insertSelective(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	List<TUser> selectByExample(TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	TUser selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TUser record, @Param("example") TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int updateByExample(@Param("record") TUser record, @Param("example") TUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int updateByPrimaryKeySelective(TUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	int updateByPrimaryKey(TUser record);
}