package com.test.mybatis.po;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.groupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.groupname
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.groupintroduce
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private String groupintroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.imgurl
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private String imgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.groupid
     *
     * @return the value of group.groupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.groupid
     *
     * @param groupid the value for group.groupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.groupname
     *
     * @return the value of group.groupname
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.groupname
     *
     * @param groupname the value for group.groupname
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.groupintroduce
     *
     * @return the value of group.groupintroduce
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public String getGroupintroduce() {
        return groupintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.groupintroduce
     *
     * @param groupintroduce the value for group.groupintroduce
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setGroupintroduce(String groupintroduce) {
        this.groupintroduce = groupintroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.imgurl
     *
     * @return the value of group.imgurl
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.imgurl
     *
     * @param imgurl the value for group.imgurl
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }
}