package com.test.mybatis.po;

import java.util.Date;

public class Ptphismes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptphismes.id
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptphismes.sender
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptphismes.receiver
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptphismes.stime
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Date stime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptphismes.isSend
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Boolean issend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptphismes.message
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptphismes.id
     *
     * @return the value of ptphismes.id
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptphismes.id
     *
     * @param id the value for ptphismes.id
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptphismes.sender
     *
     * @return the value of ptphismes.sender
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptphismes.sender
     *
     * @param sender the value for ptphismes.sender
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptphismes.receiver
     *
     * @return the value of ptphismes.receiver
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptphismes.receiver
     *
     * @param receiver the value for ptphismes.receiver
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptphismes.stime
     *
     * @return the value of ptphismes.stime
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptphismes.stime
     *
     * @param stime the value for ptphismes.stime
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptphismes.isSend
     *
     * @return the value of ptphismes.isSend
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Boolean getIssend() {
        return issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptphismes.isSend
     *
     * @param issend the value for ptphismes.isSend
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setIssend(Boolean issend) {
        this.issend = issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptphismes.message
     *
     * @return the value of ptphismes.message
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptphismes.message
     *
     * @param message the value for ptphismes.message
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setMessage(String message) {
        this.message = message;
    }
}