package com.test.mybatis.po;

public class TUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.userid
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.tnum
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private String tnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.emaile
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private String emaile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.phone
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.name
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.isonline
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private Boolean isonline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.touxiang
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	private String touxiang;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.userid
	 * @return  the value of t_user.userid
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.userid
	 * @param userid  the value for t_user.userid
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.tnum
	 * @return  the value of t_user.tnum
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public String getTnum() {
		return tnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.tnum
	 * @param tnum  the value for t_user.tnum
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setTnum(String tnum) {
		this.tnum = tnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.emaile
	 * @return  the value of t_user.emaile
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public String getEmaile() {
		return emaile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.emaile
	 * @param emaile  the value for t_user.emaile
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setEmaile(String emaile) {
		this.emaile = emaile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.phone
	 * @return  the value of t_user.phone
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.phone
	 * @param phone  the value for t_user.phone
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
	 * @return  the value of t_user.password
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
	 * @param password  the value for t_user.password
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.name
	 * @return  the value of t_user.name
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.name
	 * @param name  the value for t_user.name
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.isonline
	 * @return  the value of t_user.isonline
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public Boolean getIsonline() {
		return isonline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.isonline
	 * @param isonline  the value for t_user.isonline
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setIsonline(Boolean isonline) {
		this.isonline = isonline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.touxiang
	 * @return  the value of t_user.touxiang
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public String getTouxiang() {
		return touxiang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.touxiang
	 * @param touxiang  the value for t_user.touxiang
	 * @mbg.generated  Fri Dec 22 14:28:06 CST 2017
	 */
	public void setTouxiang(String touxiang) {
		this.touxiang = touxiang;
	}
}