package com.test.mybatis.po;

public class Usergroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.usergroupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer usergroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.userid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.groupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer groupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.ename
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usergroup.unreadnum
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    private Integer unreadnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.usergroupid
     *
     * @return the value of usergroup.usergroupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getUsergroupid() {
        return usergroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.usergroupid
     *
     * @param usergroupid the value for usergroup.usergroupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setUsergroupid(Integer usergroupid) {
        this.usergroupid = usergroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.userid
     *
     * @return the value of usergroup.userid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.userid
     *
     * @param userid the value for usergroup.userid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.groupid
     *
     * @return the value of usergroup.groupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.groupid
     *
     * @param groupid the value for usergroup.groupid
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.ename
     *
     * @return the value of usergroup.ename
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.ename
     *
     * @param ename the value for usergroup.ename
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usergroup.unreadnum
     *
     * @return the value of usergroup.unreadnum
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public Integer getUnreadnum() {
        return unreadnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usergroup.unreadnum
     *
     * @param unreadnum the value for usergroup.unreadnum
     *
     * @mbg.generated Fri Dec 22 14:28:06 CST 2017
     */
    public void setUnreadnum(Integer unreadnum) {
        this.unreadnum = unreadnum;
    }
}